// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrikjjhncnrvphtvvagc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyaWtqamhuY25ydnBodHZ2YWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDY0MTUsImV4cCI6MjA2MDA4MjQxNX0.vaGDBk1s51kwCJr89ZpICVzcmuroLI7IwUtniToz4K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);